language: php

sudo: false

env:
  global:
    - secure: "q92e8zyuFWPIg7J64GHdaHh9xiJ0seWYn/TWk+hW14EwEFJRFYx97SS6sYQAG7b2QdpeaI4c4jmVmCMniQH6aDTanODILFieFypddirTsSdwTmd5DQcAvnXvj6FnF8RU0fFsjcLpNBWnWtGeG9zeorlyYQzYIXZtYNX4yqfDBDYod6pFw/fJavbRdal4UBZVDQrWfKj8ei2O02cYtWPwlTacM99/QLF3h438NnG6T6uiWjQWGGQ2KmN90hCzviRHYsscsRyPRCfkW5qIsxrm4pRTEDHU/zmB9jFTGj8QDzhoMEm1947trVWxH9UGIQXYJLI40HQkOPXAGBByO+AAWkcOuy+SoubFsQJ63p1qmAFuxhsc+0pFVuC6Jl0K64SS6GxQOENXZpLMZ3Jbfc6EmtJeWjt8h73oEAMEz6QKPIV9zdSDITY1Gnms/QWZ5gUzvfqaGWxnF/jRUX7naTIJqAKELVQohHxhYlkYqv9p++tNlXogm6R+tTOPkN7WjGnKmu+B+DjsQg430VlajkkL8aTWqbzT5RuI5uNYCURz1++gVIZJrVpO+rdjuKVjCCLUevtuAEoq1LEe25oX3vvq6OnftWXhJlzaPDUg+/OA6CN4sXIeZ4n6IKSKg6C7JlmzVMHROLiG9P1x8ZeNG4xQUl5mKrsnN1Lm7dUkDpUONx8="
    - secure: "DE52JA+TV64tcX8C3G/SBWy695SQJ899e+3oUJMiAS9FaTSpFCRAXf4Y/63X/n0OZmCA+klCVc5kEag4A4Le51e9TyT8Mr6j9WIvAnih/4VqQD+hO2pc7avoTzmqJKB5APUnNVGqztectVYWnH5o3PNuPuSWeH/uYKv18qxgxFa12V78burqbpDWPStcwweeXAq0/xLshUIavvlhApOKPWk9LIxfj14FymCuvPehEc5ARffjRWA996VK2oYYnpcVY8JymdEg/dtOhV7kvuCQflgupaYNOGdOSVUqp6HQn5UxygWYMHMybs1Nnc/99o27Ff6TjB7FLANpNZTG2jOYAAaVQw971ywQziGGN8t1rFo9m6K7kcPhd1Cpq5FOXMVbAbYGeVq5c34/E3DdIPbZGQDDzLygu2AgXqiP0EK6KIwPH6fdNSS6fV9tJ8ECg+UTcvR5kM85u/Df6MrLeiPwO75NrZPfYjuOK4+8y2jZu3WDgI/4eAeBqdiF6AE1bo3CNDeGyxb3Sh6BLhS15ngS/Io0qgigwgO+rI+wDElXnNa2Kop72EWOah3ZJncueixDtlguYzS+DRKjxGmlQ9z9VJ9JbEv9k+xQZ9Z15V6YVEi2/u31bHz8wyVge2rTZZ5LuV+nDxeO3Lvy4NZPrQVEPANo3TaQh8dhyMa81aixg6Q="

matrix:
  include:
    - php: 5.5
    - php: 5.6
      env: REPORT_COVERAGE=true
    - php: 7
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - composer self-update
  - composer validate
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - composer install --prefer-dist

before_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then IS_MERGE_TO_MASTER=true; else IS_MERGE_TO_MASTER=false; fi
  - mkdir -p $HOME/.php-cs-fixer

script:
  - if [[ "$REPORT_COVERAGE" == "true" && "$IS_MERGE_TO_MASTER" == "true" ]]; then vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --configuration phpunit.xml; fi
  - vendor/bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run

after_success:
  - if [[ "$REPORT_COVERAGE" == "true" && "$IS_MERGE_TO_MASTER" == "true" ]]; then bin/report-coverage; fi
